---
title: "Luminex Assay Plots"
output: html_document

params:
  rp_upload_data: NA
  rp_ref_idf_str: NA
  rp_combined_data: NA
  rp_combined_meta: NA
---

```{r eval = FALSE, echo = FALSE}
# For PDF output, change the header to have "output: pdf_document".
#
# Note that due to an issue in rmarkdown, the default value of a parameter in
# the header cannot be `NULL`, so I used a default of `NA` for the default value
# of `n`.
library(dplyr)
library(DT)
```


## Summary of plate level information.


```{r, echo=F, message=F, warning=F}
DT::datatable(
      data.frame(filename = sapply(params$rp_upload_data, function(x) x$File[1]) %>% unlist(),
                 #panel = sapply(params$rp_upload_data, function(x) x@metadata$panel)%>% unlist(),
                 total_samples = sapply(params$rp_upload_data, function(x) ncol(x)) %>% unlist(),
                 total_analyte = sapply(params$rp_upload_data, function(x) nrow(x)) %>% unlist()),
      rownames = NULL,
      options = list(scrollX = TRUE))
```
 
### Reference sample identifier: `r paste(strsplit(params$rp_ref_idf_str, split = ","), collapse = ",")`

```{r, echo=F, message=F, warning=F}
# needs sample_id, Plate.ID, in metafile and "lot" only appear once in column names

lapply(strsplit(params$rp_ref_idf_str, split = ",")%>%unlist(), function(x){
      bdg_ls <- pull_bdg(params$rp_upload_data, pattern = x)
      data.frame(filename = names(bdg_ls),
                 identifier = x,
                 total_samples = sapply(bdg_ls, function(x) ncol(x)) %>% unlist(),
                 details = sapply(bdg_ls, function(x) paste(x$Sample, collapse = ",")) %>% unlist())
    })%>%
      do.call(what = "rbind")%>%
      DT::datatable(rownames = NULL,
      options = list(scrollX = TRUE))

```

### Reference trace plot

**`r if(length(params$rp_upload_data) == 1) {paste("Reference trace plot not applicable to single plate.")}`**    


```{r, echo=F, out.width= "100%", message=F, warning=F}
# needs sample_id, File, in metafile and "lot" only appear once in column names

df <- lapply(strsplit(params$rp_ref_idf_str, split = ",")%>%unlist(), function(x){
    data.frame(Plate.ID = trim_string_bycommon(params$rp_combined_meta$File, split = "_"),
               sample_id = params$rp_combined_meta$Sample,
               t(params$rp_combined_data@assays@data$data_imputed))%>%
      filter(grepl(x, sample_id, ignore.case = T))%>%
      mutate(Sample = x)
  })%>%
  do.call(what = "rbind")
  
  
  # tracking plot
  if(length(unique(df$Plate.ID)) > 1){
    print(df%>%
    select(-sample_id)%>%
    gather(-Plate.ID, -Sample, key = "analyte", value = "conc.")%>%
    ggplot(aes(Plate.ID, log10(conc.)))+
    geom_line(aes(group = analyte))+
    facet_wrap(~Sample)+ 
    labs(subtitle = "each line indicate a analyte")+
    theme_bw()+
    theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
          legend.position="bottom", legend.box="vertical", legend.margin=margin()))
  }
```

### Out of Range sample summary  


```{r, echo=F, out.width= "100%", message=F, warning=F, results="hide"}
cmb <- params$rp_combined_data

if(length(params$rp_upload_data) > 1){
  cmb@elementMetadata$LOD <- NULL
  cmb@elementMetadata$HOD <- NULL
}
lod <- data.frame(analyt = rownames(cmb),
                lapply(names(cmb@elementMetadata)[grep("(LOD_|LOD)", names(cmb@elementMetadata))], function(x){
                  cmb@elementMetadata[[x]]
                })%>%
                  do.call(what = "cbind")%>%
                  set_colnames(value = unique(cmb$File))
                )%>%
gather(-analyt, key = "File", value = "lod")%>%
mutate(File = trim_string_bycommon(File, split = "_"))

hod <- data.frame(analyt = rownames(cmb),
                  lapply(names(cmb@elementMetadata)[grep("(HOD_|HOD)", names(cmb@elementMetadata))], function(x){
                    cmb@elementMetadata[[x]]
                  })%>%
                    do.call(what = "cbind")%>%
                    set_colnames(value = unique(cmb$File))
                  )%>%
  gather(-analyt, key = "File", value = "hod")%>%
  mutate(File = trim_string_bycommon(File, split = "_"))


plotdf <- data.frame(Sample = cmb$Sample,
                     File = cmb$File,
                     t(cmb@assays@data$data_imputed))%>%
  mutate(Type = ifelse(grepl("QC", Sample, ignore.case = T), "QC", "StudySample"))%>%
  gather(-Sample, -Type, -File, key = "analyte", value = "value")%>%
  mutate(File = trim_string_bycommon(File, split = "_"))
```



```{r, echo=F, out.width= "100%", message=F, warning=F}

query <- trim_string_bycommon(names(params$rp_upload_data), split = "_")

plot.ls <- lapply(1 : length(query), function(x){
  # out of range barplot
  sub_tit = paste(query[x], "\ntotal sample on plates:\n", ncol(params$rp_upload_data[[x]]))

  p1 <- data.frame(Sample = params$rp_upload_data[[x]]$Sample,
                     t(params$rp_upload_data[[x]]@assays@data$data_default))%>%
    gather(-Sample, key = "analyte", value = "value")%>%
    group_by(analyte)%>%
    summarise(out_of_range_count = sum(!is.finite(value)))%>%
    ggplot(aes(analyte, out_of_range_count))+
    geom_bar(stat = "identity", alpha = 0.7)+
    geom_text(aes(label = out_of_range_count))+
    coord_flip()+
    labs(subtitle = sub_tit)+
    theme_bw(base_size = 8)
  
})

wrap_plots(plot.ls, ncol = 1)
```

### sample distribution plot
**Blue line indicate LLOD**       
**Red line indicate HLOD**   

```{r, echo=F, out.width= "100%", message=F, warning=F, results="hide"}

plot.ls <- lapply(unique(plotdf$analyte), function(x){

  tit = x
  plotdf%>%
  filter(analyte == x)%>%
  ggplot(aes(Type, log10(value)))+
  geom_jitter()+
  #ggrepel::geom_text_repel(aes(label = Sample), size = 3)+
  geom_segment(aes(x = 0.5, xend = 2.5, y = log10(lod), yend = log10(lod)),
               color = "blue",
               data = lod %>% filter(analyt == x))+
  geom_segment(aes(x = 0.5, xend = 2.5, y = log10(hod), yend = log10(hod)),
             color = "red",
             data = hod %>% filter(analyt == x))+
  labs(title = tit, y = "log Conc.", x = "")+
  facet_wrap(~File, ncol = 3)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5, size = 8))
})
  

if(length(params$rp_upload_data) > 1){
  for(i in 1 : length(plot.ls)){
    print(
        plot.ls[i]
      )
  }
}else{
  per_panel <- 6
  n_panel <- ceiling(length(plot.ls)/per_panel)

  for (i in 1 : n_panel) {
    print(
      wrap_plots(plot.ls[(1 + (i-1) * per_panel) : min(length(plot.ls), (per_panel + (i-1) * per_panel))],
                 ncol = 3, nrow = 2, byrow = T, guides = "collect")& theme(legend.position = 'bottom')
    )
  }
}

```

